apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-volume1
  labels:
    pv: nginx-pv-volume1
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/d/douyu_projects/mogo2/mogo/k8s_yaml/data/nginx/conf/nginx.conf"